version: '3'

networks:
  ggb-network:
    external: true

services:
  rcssserver:
    tty: true
    container_name: rcssserver
    image: orangefoil/rcssserver
    networks:
      - ggb-network
    ports:
      - 6000:6000/udp
    logging:
      options:
       max-size: 50m

  ggb-team:
    tty: true
    container_name: ggb-team
    image: golang:latest
    working_dir: /opt/go/src/github.com/samuelvenzi/rcss-ggb/ggb-team
    command: "go run main.go"
    volumes:
      - ./ggb-team:/opt/go/src/github.com/samuelvenzi/rcss-ggb/ggb-team
    networks:
      - ggb-network
    logging:
      options:
       max-size: 50m
    depends_on:
      - rcssserver
