version: '3'

networks:
  ggb-network:
    external: true

services:
  rcssserver:
    tty: true
    container_name: rcssserver
    image: rcssggb/rcssserver:latest
    networks:
      - ggb-network
    ports:
      - 6000:6000/udp
    logging:
      options:
       max-size: 50m

  rcssmonitor:
    tty: true
    container_name: rcssmonitor
    image: rcssggb/rcssmonitor:latest
    networks:
      - ggb-network
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    logging:
      options:
       max-size: 50m
    depends_on:
      - rcssserver

  ggb-team:
    tty: true
    container_name: ggb-team
    image: golang:latest
    working_dir: /go/src/github.com/samuelvenzi/rcss-ggb/ggb-team
    command: "go run main.go"
    volumes:
      - ./ggb-team:/go/src/github.com/samuelvenzi/rcss-ggb/ggb-team
    networks:
      - ggb-network
    logging:
      options:
       max-size: 50m
    depends_on:
      - rcssserver
