FROM ubuntu:18.04 AS build
ARG VERSION=15.2.1
WORKDIR /root

RUN apt update && \
    apt -y install autoconf bison clang flex libboost-dev libboost-all-dev libc6-dev make wget libqt4-dev 

RUN wget https://github.com/rcsoccersim/rcssmonitor/releases/download/rcssmonitor-${VERSION}/rcssmonitor-${VERSION}.tar.gz && \
    tar xfz rcssmonitor-${VERSION}.tar.gz && \
    ls && \
    cd rcssmonitor-${VERSION} && \
    ./configure && \
    make && \
    make install 

FROM ubuntu:18.04

COPY --from=build /usr/local/lib /usr/local/lib
COPY --from=build /usr/local/bin /usr/local/bin

CMD ["/usr/local/bin/rcssmonitor"]